{
 "title": "Planetarium",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "query0", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 } }
   ]
  },
  { "title": "Rate of Change: Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Latency 5mins",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{job=\"planetarium-clusterip\"}[5m])) / sum(rate(http_server_requests_seconds_count{job=\"planetarium-clusterip\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 15mins",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{job=\"planetarium-clusterip\"}[15m])) / sum(rate(http_server_requests_seconds_count{job=\"planetarium-clusterip\"}[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 30mins",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{job=\"planetarium-clusterip\"}[30m])) / sum(rate(http_server_requests_seconds_count{job=\"planetarium-clusterip\"}[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 60mins",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{job=\"planetarium-clusterip\"}[60m])) / sum(rate(http_server_requests_seconds_count{job=\"planetarium-clusterip\"}[60m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Rate of Change: Success Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Success Rate 5mins",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"planetarium-clusterip\", outcome!=\"SERVER_ERROR\"}[5m])) / sum(rate(http_server_requests_seconds_count{job=\"planetarium-clusterip\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate 15mins",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"planetarium-clusterip\", outcome!=\"SERVER_ERROR\"}[15m])) / sum(rate(http_server_requests_seconds_count{job=\"planetarium-clusterip\"}[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate 30mins",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"planetarium-clusterip\", outcome!=\"SERVER_ERROR\"}[30m])) / sum(rate(http_server_requests_seconds_count{job=\"planetarium-clusterip\"}[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate 60mins",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"planetarium-clusterip\", outcome!=\"SERVER_ERROR\"}[1h])) / sum(rate(http_server_requests_seconds_count{job=\"planetarium-clusterip\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "99th Percentile Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "99 Percentile Latency in 5mins",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{job=\"planetarium-clusterip\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99 Percentile Latency in 15mins",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{job=\"planetarium-clusterip\"}[15m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99 Percentile Latency in 30mins",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{job=\"planetarium-clusterip\"}[30m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99 Percentile Latency in 60mins",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{job=\"planetarium-clusterip\"}[1h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": " Loki", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Planetarium ERROR Logs",
   "type": "logs",
   "gridPos": { "h": 20, "w": 8, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "{job=\"planetarium-logs\"} |= `ERROR`"
    }
   ]
  },
  {
   "title": "Planetarium WARN Logs",
   "type": "logs",
   "gridPos": { "h": 20, "w": 8, "x": 8, "y": 38 },
   "targets": [
    {
     "expr": "{job=\"planetarium-logs\"} |= `WARN`"
    }
   ]
  },
  {
   "title": "Planetarium INFO Logs",
   "type": "logs",
   "gridPos": { "h": 20, "w": 8, "x": 16, "y": 38 },
   "targets": [
    {
     "expr": "{job=\"planetarium-logs\"} |= `INFO`"
    }
   ]
  },
  { "title": "Static", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Total Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"planetarium-clusterip\", outcome!=\"SERVER_ERROR\"}) / sum(http_server_requests_seconds_count{job=\"planetarium-clusterip\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Avg Latency",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{job=\"planetarium-clusterip\"} / http_server_requests_seconds_count{job=\"planetarium-clusterip\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}